version: '3'

services:
  gamingwebapp:
    image: xpiritbv/gamingwebapp:latest
    depends_on:
      - "leaderboardwebapi"
    networks:
      - shared
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - LeaderboardApiOptions__BaseUrl=http://leaderboardwebapi
    ports:
      - "80:8080"

  leaderboardwebapi:
    image: xpiritbv/leaderboard.webapi:latest
    depends_on:
      - "sql"
    networks:
      - shared
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:8080
      - ConnectionStrings__LeaderboardContext=Server=sql;Database=Leaderboard;User Id=sa;Password=Pass@word;Trusted_Connection=False
    ports:
      - "80:8080"

  sql:
    image: mcr.microsoft.com/mssql/server
    networks:
      - shared
    environment:
      - SA_PASSWORD=Pass@word
      - MSSQL_PID=Developer
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"

networks:
  shared:
    driver: bridge